united-build: 
language: generic
sudo: false
services:
- docker
#before_install:
#- docker pull davidva/unibuild
# docker ps -a
# docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"
#cache:
#  directories:
#    - /var/cache/mock/
script:
#- travis_wait 40 docker run --cap-add=SYS_ADMIN --privileged=true -v $(pwd):/root/enjoy/ davidva/unibuild /bin/sh /urpms -g UnitedRPMs/opera -s opera.spec -t fedora-24-x86_64
- travis_wait 40 docker run --cap-add=SYS_ADMIN davidva/unibuild /bin/sh /urpms -g UnitedRPMs/opera -s opera.spec -t fedora-25-x86_64
notifications:
  email: davidva@tutanota.com
##  slack: unitedrpms:lzDykHTpajKrgmGz9NkrO1Hj

