FROM davidva/usync

MAINTAINER David Va <davidva@tutanota.com>

RUN rm -rf united-build \ 
&& git clone https://github.com/kuboosoft/united-build.git \
&& cd united-build \
&& chmod a+x sync-united \
&& ./sync-united -s repository \
&& ./sync-united -s 25 \
&& ./sync-united -s 26 

VOLUME ["/var/lib/mock"]

USER root
CMD ["/bin/bash"]



